### ISSUE TITLE
Do not set permissions for jobs with GITHUB_TOKEN in job level env variable

### ISSUE THREAD

**Issue by varunsh-coder** [step-security/secure-repo#2479]
There is an error condition to not set permissions for jobs with GITHUB_TOKEN in step level env variable
https://github.com/step-security/secure-repo/blob/d61982f516cebd6559d547417e558a8cd57dd9f5/remediation/workflow/permissions/permissions.go#L35

But if env variable is set at job level, the code sets token permissions. These may be incorrect as the specific logic to determine the permissions is not known. 

Here is a test workflow
```
name: Job level env
on:
  pull_request:
    branches: [main]

jobs:
  Lint:
    env:
      GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
    runs-on: ubuntu-latest
    steps:
      
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
      - name: some step that uses token
        run: |
          npm ci
```
